### ISSUE TITLE
nei build构建iOS工程时报错

### ISSUE THREAD

**Issue by agger0207** [NEYouFan/nei-toolkit#19]
在build.json同目录下执行命令如下：

```
nei build 11321 -c build.json --productName HTTestPluginDemo --namePrefix HTP --Prefix HTP --CategoryPrefix htp
```

错误如下：

```

HTExample/HTTestPluginDemo/HTTestPluginDemo/Network/Requests/HTPRequests.h
/usr/local/lib/node_modules/nei/lib/nei/mobile.oc.pbx.js:25
        group.children.forEach((file) => {
             ^

TypeError: Cannot read property 'children' of undefined
    at PbxProj.removeGroupFiles (/usr/local/lib/node_modules/nei/lib/nei/mobile.oc.pbx.js:25:14)
    at PbxProj.createPBXGroupByFullPath (/usr/local/lib/node_modules/nei/lib/nei/mobile.oc.pbx.js:145:18)
    at PbxProj.update (/usr/local/lib/node_modules/nei/lib/nei/mobile.oc.pbx.js:240:18)
    at MobileOCBuilder.modelStart (/usr/local/lib/node_modules/nei/lib/nei/mobile.oc.js:399:25)
    at MobileOCBuilder.buildStart (/usr/local/lib/node_modules/nei/lib/nei/mobile.oc.js:427:26)
    at MobileOCBuilder.start (/usr/local/lib/node_modules/nei/lib/nei/builder.js:519:14)
    at MobileOCBuilder.build (/usr/local/lib/node_modules/nei/lib/nei/mobile.js:196:19)
    at loadData (/usr/local/lib/node_modules/nei/main.js:124:28)
    at _io.download (/usr/local/lib/node_modules/nei/main.js:37:17)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/nei/lib/util/io.js:176:17)

```

**Comment by agger0207** [comment]
fixed in v0.4.5.
