### ISSUE TITLE
运行server命令出错

### ISSUE THREAD

**Issue by claudia007** [NEYouFan/nei-toolkit#37]
运行 
```nei server -k cec47ff7e9d51d1db545f4af92362866  -o ./todoweb```
出现报错：

```
/Users/TEST/.nvm/versions/node/v6.3.0/lib/node_modules/nei/node_modules/serve-static/index.js:40
    throw new TypeError('root path required')
    ^

TypeError: root path required
    at Function.serveStatic [as static] (/Users/TEST/.nvm/versions/node/v6.3.0/lib/node_modules/nei/node_modules/serve-static/index.js:40:11)
    at Object.Server.init (/Users/TEST/.nvm/versions/node/v6.3.0/lib/node_modules/nei/lib/server/main.js:82:31)
    at Object.Server (/Users/TEST/.nvm/versions/node/v6.3.0/lib/node_modules/nei/lib/server/main.js:18:10)
    at module.exports (/Users/TEST/.nvm/versions/node/v6.3.0/lib/node_modules/nei/lib/server/server.js:72:18)
    at tryStartServer (/Users/TEST/.nvm/versions/node/v6.3.0/lib/node_modules/nei/main.js:103:17)
    at Main.server (/Users/TEST/.nvm/versions/node/v6.3.0/lib/node_modules/nei/main.js:125:13)
    at Args.options.server (/Users/TEST/.nvm/versions/node/v6.3.0/lib/node_modules/nei/bin/nei.js:43:14)
    at emitOne (events.js:96:13)
    at Args.emit (events.js:188:7)
```
请问该怎么解决？

**Comment by huntbao** [comment]
这个错误是由于没有设置“静态资源根目录”引起的，有 2 种解决方法：

1. 在工程规范里面添加一个目录，然后将它设置为“静态资源根目录”
2. 将工具升级到最新版本

**Comment by claudia007** [comment]
@huntbao 
好的，谢谢~已经解决
