### ISSUE TITLE
接口测试 测试用例 文件上传不能成功

### ISSUE THREAD

**Issue by duyueping** [NEYouFan/nei-toolkit#53]
后端不能接收到文件流

**Comment by huntbao** [comment]
@duyueping 这个问题已经在看了，有结果我再来回复

**Comment by huntbao** [comment]
@duyueping 文件已经可以发送，请更新 [XHRProxyTool](https://chrome.google.com/webstore/detail/fbakmpanchidgmjopcmcddoihgjkfcjn) 至最新版本 ` 1.4.6`

**Comment by duyueping** [comment]
@huntbao 还是不行 一直提交中 不动了 扩展已经更新至1.4.6

**Comment by huntbao** [comment]
@duyueping 后端接口没接收到文件？

右键扩展程序的图标，选择“管理扩展程序”，打开 检查视图后面的“背景页”。然后看下网络请求，有没有发送文件。

**Comment by duyueping** [comment]
@huntbao 

管理扩展程序的页面没有任何请求 倒是测试用例页面报错如下

chrome-extension://bclmkgofhdgekpoamoialodjdloiilod/content.js:390 undefined
core_52507ce9c0b478cbc0b00362d526c599.js:36 接口用例-请求信息(原始): Object
core_52507ce9c0b478cbc0b00362d526c599.js:36 接口用例-请求信息(转义后): Object
core_52507ce9c0b478cbc0b00362d526c599.js:37 接口用例-请求信息(发送给xhr proxy): Object
extensions::schemaUtils:112 Uncaught Error: Invocation of form runtime.connect() doesn't match definition runtime.connect(optional string extensionId, optional object connectInfo)
    at Object.normalizeArgumentsAndValidate (extensions::schemaUtils:112:11)
    at Object.<anonymous> (extensions::binding:411:30)
    at HTMLDocument.<anonymous> (chrome-extension://fbakmpanchidgmjopcmcddoihgjkfcjn/js/xhrproxy.page.js:1:508)
extensions::schemaUtils:112 Uncaught Error: Invocation of form runtime.connect() doesn't match definition runtime.connect(optional string extensionId, optional object connectInfo)
    at Object.normalizeArgumentsAndValidate (extensions::schemaUtils:112:11)
    at Object.<anonymous> (extensions::binding:411:30)
    at chrome-extension://fbakmpanchidgmjopcmcddoihgjkfcjn/js/xhrproxy.page.js:1:622
core_52507ce9c0b478cbc0b00362d526c599.js:36 接口用例-请求信息(原始): Object
core_52507ce9c0b478cbc0b00362d526c599.js:36 接口用例-请求信息(转义后): Object
core_52507ce9c0b478cbc0b00362d526c599.js:37 接口用例-请求信息(发送给xhr proxy): Object
extensions::schemaUtils:112 Uncaught Error: Invocation of form runtime.connect() doesn't match definition runtime.connect(optional string extensionId, optional object connectInfo)
    at Object.normalizeArgumentsAndValidate (extensions::schemaUtils:112:11)
    at Object.<anonymous> (extensions::binding:411:30)
    at HTMLDocument.<anonymous> (chrome-extension://fbakmpanchidgmjopcmcddoihgjkfcjn/js/xhrproxy.page.js:1:508)
extensions::schemaUtils:112 Uncaught Error: Invocation of form runtime.connect() doesn't match definition runtime.connect(optional string extensionId, optional object connectInfo)
    at Object.normalizeArgumentsAndValidate (extensions::schemaUtils:112:11)
    at Object.<anonymous> (extensions::binding:411:30)
    at chrome-extension://fbakmpanchidgmjopcmcddoihgjkfcjn/js/xhrproxy.page.js:1:622
core_52507ce9c0b478cbc0b00362d526c599.js:36 接口用例-请求信息(原始): Object
core_52507ce9c0b478cbc0b00362d526c599.js:36 接口用例-请求信息(转义后): Object
core_52507ce9c0b478cbc0b00362d526c599.js:37 接口用例-请求信息(发送给xhr proxy): Object
extensions::schemaUtils:112 Uncaught Error: Invocation of form runtime.connect() doesn't match definition runtime.connect(optional string extensionId, optional object connectInfo)
    at Object.normalizeArgumentsAndValidate (extensions::schemaUtils:112:11)
    at Object.<anonymous> (extensions::binding:411:30)
    at HTMLDocument.<anonymous> (chrome-extension://fbakmpanchidgmjopcmcddoihgjkfcjn/js/xhrproxy.page.js:1:508)
extensions::schemaUtils:112 Uncaught Error: Invocation of form runtime.connect() doesn't match definition runtime.connect(optional string extensionId, optional object connectInfo)
    at Object.normalizeArgumentsAndValidate (extensions::schemaUtils:112:11)
    at Object.<anonymous> (extensions::binding:411:30)
    at chrome-extension://fbakmpanchidgmjopcmcddoihgjkfcjn/js/xhrproxy.page.js:1:622

**Comment by n0ruSh** [comment]
@duyueping 有可能是下面2个原因。

1. 扩展更新后没有刷新页面。https://github.com/extesy/hoverzoom/issues/243
2. 接口的定义里加个content-type: multipart-formdata

如果不是上面这2个原因的话。加下我qq 262052637具体看下把。
