### ISSUE TITLE
nei iOS 配置出错

### ISSUE THREAD

**Issue by wjssxc** [NEYouFan/nei-toolkit#55]
/usr/local/lib/node_modules/nei/lib/nei/builder.js:472
        if (this.config.jarRoot || this.spec.jarConfig.length > 0) {
                                                      ^

TypeError: Cannot read property 'length' of undefined
    at Builder.buildServerConfig (/usr/local/lib/node_modules/nei/lib/nei/builder.js:472:55)
    at new Builder (/usr/local/lib/node_modules/nei/lib/nei/builder.js:77:18)
    at loadedHandler (/usr/local/lib/node_modules/nei/main.js:46:13)
    at _io.download.ex (/usr/local/lib/node_modules/nei/main.js:178:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/nei/lib/util/io.js:178:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
请问这个问题是怎么引起的么？

**Comment by AbnerZheng** [comment]
你好，你的工程规范的模板设置为什么呢？

**Comment by wjssxc** [comment]
我设了ht-networking-V3-POCT，还有之前iOS的模版我都设置了，但是都出现这个问题，request没内容

**Comment by AbnerZheng** [comment]
是网易的同事吗?可以加我popo， hzzhenglu
