### ISSUE TITLE
nei build报错

### ISSUE THREAD

**Issue by zyqhi** [NEYouFan/nei-toolkit#60]
创建一个demo项目，想要模拟一下iOS的Request和Model自动生成，但是在build的时候报错：

命令：

```
 nei build  -sk fe11bab766bc8670f78a06f9ba728a63
```

错误信息：

```
[I] 2017-09-02 13:22:23.964 - 从 NEI 服务器加载数据, 地址: https://nei.netease.com/api/specificationres/?key=fe11bab766bc8670f78a06f9ba728a63
[I] 2017-09-02 13:22:24.044 - 数据加载完成, 开始解析数据
[D] 2017-09-02 13:22:24.217 - 文件已存在, 不覆盖: /Users/mutsu/project/apple/iOS/NEICodeGenTest/NEICodeGenTest/Network/Requests/outputModelFilterHelper.js
[D] 2017-09-02 13:22:24.266 - 文件已存在, 不覆盖: /Users/mutsu/project/apple/iOS/NEICodeGenTest/NEICodeGenTest/Network/Requests/requestJSONStringify.js
[D] 2017-09-02 13:22:24.353 - 文件已存在, 不覆盖: /Users/mutsu/project/apple/iOS/NEICodeGenTest/NEICodeGenTest/Network/Requests/Requests.h
[E] 2017-09-02 13:22:24.400 - 生成文件错误: Error: Missing helper: "requestJSONStringify"
[D] 2017-09-02 13:22:24.400 - 文件已存在, 不覆盖: /Users/mutsu/project/apple/iOS/NEICodeGenTest/NEICodeGenTest/Network/Requests/.h
[E] 2017-09-02 13:22:24.477 - 生成文件错误: Error: Missing helper: "modelFilterHelper"
[D] 2017-09-02 13:22:24.477 - 文件已存在, 不覆盖: /Users/mutsu/project/apple/iOS/NEICodeGenTest/NEICodeGenTest/Network/Requests/.m
[D] 2017-09-02 13:22:24.569 - 文件已存在, 不覆盖: /Users/mutsu/project/apple/iOS/NEICodeGenTest/NEICodeGenTest/Network/Models/baseStrHelper.js
[D] 2017-09-02 13:22:24.630 - 文件已存在, 不覆盖: /Users/mutsu/project/apple/iOS/NEICodeGenTest/NEICodeGenTest/Network/Models/dictStrHelper.js
[D] 2017-09-02 13:22:24.698 - 文件已存在, 不覆盖: /Users/mutsu/project/apple/iOS/NEICodeGenTest/NEICodeGenTest/Network/Models/iosProperty.js
[D] 2017-09-02 13:22:24.751 - 文件已存在, 不覆盖: /Users/mutsu/project/apple/iOS/NEICodeGenTest/NEICodeGenTest/Network/Models/Models.h
[D] 2017-09-02 13:22:24.810 - 文件已存在, 不覆盖: /Users/mutsu/project/apple/iOS/NEICodeGenTest/NEICodeGenTest/Network/Models/.h
[E] 2017-09-02 13:22:24.869 - 生成文件错误: Error: Missing helper: "dictStrHelper"
[D] 2017-09-02 13:22:24.869 - 文件已存在, 不覆盖: /Users/mutsu/project/apple/iOS/NEICodeGenTest/NEICodeGenTest/Network/Models/.m
[D] 2017-09-02 13:22:24.904 - 文件已存在, 不下载: /Users/mutsu/project/apple/iOS/NEICodeGenTest/NEICodeGenTest/Network/Models/.h!!enum
[D] 2017-09-02 13:22:24.954 - 文件已存在, 不覆盖: /Users/mutsu/project/apple/iOS/NEICodeGenTest/NEICodeGenTest/Network/config.json
```

没有一个demo吗，展示一下整个代码自动化生成的流程？有点搞不清楚怎么把NEI上接口规范转换成本地的代码。试图运行如下命令：

```
nei build -k 1e1859a5704059aa8db510593c1efe29 -sk fe11bab766bc8670f78a06f9ba728a63
```

则报如下错误：

```
[I] 2017-09-02 11:35:40.633 - 从 NEI 服务器加载数据, 地址: https://nei.netease.com/api/specificationres/?key=fe11bab766bc8670f78a06f9ba728a63
[I] 2017-09-02 11:35:40.714 - 数据加载完成, 开始解析数据
[D] 2017-09-02 11:35:40.823 - 输出: /Users/mutsu/project/apple/iOS/NEICodeGenTest/NEICodeGenTest/nei.10933.1e1859a5704059aa8db510593c1efe29/json/nei-2017-09-02-11-35-40-820.json
[D] 2017-09-02 11:35:40.823 - 输出: /Users/mutsu/project/apple/iOS/NEICodeGenTest/NEICodeGenTest/nei.10933.1e1859a5704059aa8db510593c1efe29/json/nei-latest.json
/usr/local/lib/node_modules/nei/lib/nei/builder.js:187
    this.options.ds.interfaces.forEach((itf) => {
                              ^

TypeError: Cannot read property 'forEach' of undefined
    at Builder.buildInterfaceMock (/usr/local/lib/node_modules/nei/lib/nei/builder.js:187:31)
    at new Builder (/usr/local/lib/node_modules/nei/lib/nei/builder.js:72:12)
    at loadedHandler (/usr/local/lib/node_modules/nei/main.js:46:7)
    at _io.download (/usr/local/lib/node_modules/nei/main.js:182:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/nei/lib/util/io.js:178:17)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

希望解答一下。

**Comment by AbnerZheng** [comment]
你应该在你的工程里指定工程规范为该工程规范，然后，生成命令用nei build -k， 而不是sk, 请参考 [文档](https://github.com/NEYouFan/nei-toolkit/blob/master/doc/%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E4%BD%BF%E7%94%A8nei%E6%9E%84%E5%BB%BAMock%E6%9C%8D%E5%8A%A1%E5%99%A8%E4%BB%A5%E5%8F%8A%E9%85%8D%E7%BD%AE%E8%B7%A8%E5%9F%9F%E5%A4%B4.md)。 注意文档中，一个是工程规范，一个是工程。我
